zoneStartSize: 2048
zonePreStartSize: 2055
zoneStartTimer: 300
zoneStartDelay: 60
zoneEndSize: 100
zoneEndSpeed: 0.5
zoneNewSizeMultiplier: 0.5
zoneProcessorPeriod: 10
zoneWaitTimerMultiplier: 0.75
zoneShrinkTimerMultiplier: 0.66
zoneCenterOffsetEnabled: true
zoneStartDamage: 0.01
zoneDamageMultiplier: 2
zoneLavaFlowSize: 16
lavaFlowPeriod: 30
redzoneEnabled: true
redzoneRadius: 25
redzonePeriod: 10
redzoneDuration: 20
redzoneDensity: 5
redzoneStartDelay: 350
redzoneDelayMin: 60
redzoneDelayMax: 120
redzoneDisableSize: 250
monstersEnabled: true
monstersStartDelay: 310
monstersSpawnChances:
  ZOMBIE: 0.5
  SKELETON: 0.5
  CREEPER: 0.5
  WITCH: 0.25
elytraStartEnabled: true
elytraFallHeight: 1600
lobbyMinVotestarters: 3
lobbyMinVotestartersPercent: 0.51
lobbyPostGameCommandEnabled: true
lobbyPostGameCommand: say post-game event triggered
lobbyPostGameCommandDelay: 60
squadMaxMembers: 4
squadNametagVisiblity: FOR_OWN_TEAM
squadFriendlyFireEnabled: true
squadAutoBalancingEnabled: true
gameOutsideBreakingEnabled: true
gameOutsideBreakingMaxDistance: 3
gameOutsideBreakingPeriod: 10
gameGiveZoneMap: true
gameContainerTrackingEnabled: true
gameContainerReplacmentMaterial: MOSSY_COBBLESTONE
airdropEnabled: true
airdropAlertEnabled: true
airdropStartDelay: 250
airdropDelayMin: 120
airdropDelayMax: 240
airdropDisableSize: 300
airdropItems:
  AIR: 200
  COBBLESTONE: 100
  ARROW: 20
  BOW: 10
  IRON_SWORD: 2
  SPLASH_POTION: 1
airdropEnchantedItemChance: 0.1
airdropEnchantments:
  BOW:
    ARROW_DAMAGE: 3
    ARROW_KNOCKBACK: 1
  IRON_SWORD:
    DAMAGE_ALL: 4
    KNOCKBACK: 1
airdropPotions:
  INSTANT_HEAL: 10
  SPEED: 8
  INSTANT_DAMAGE: 5
  STRENGTH: 4
airdropStackableItems:
  ARROW: 16
  COBBLESTONE: 64
