name: BattleRoyale
main: ru.sooslick.royale.royale
version: 0.2.1.1
author: sooslick
commands:
  royale:
    description: manages royale game
    usage: /royale [command]
  zone:
    description: returns current gamezone info
    aliases: z
    usage: /zone
  votestart:
    description: vote to launch royale game
    aliases: [v, vs]
    usage: /votestart
  squad:
    description: manages player's squads
    usage: /squad [command]
  rlconfig:
    description: manage BattleRoyale configuration
    usage: /rlconfig